// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driverservice.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Lastlogin            int64    `protobuf:"varint,4,opt,name=lastlogin,proto3" json:"lastlogin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d91fe6e1e35535, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastlogin() int64 {
	if m != nil {
		return m.Lastlogin
	}
	return 0
}

type Response struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	IsOK                 bool     `protobuf:"varint,2,opt,name=isOK,proto3" json:"isOK,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d91fe6e1e35535, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetIsOK() bool {
	if m != nil {
		return m.IsOK
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LocationRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d91fe6e1e35535, []int{2}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LocationRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LocationRequest) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *LocationRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetLocationRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SourceLat            float64  `protobuf:"fixed64,2,opt,name=sourceLat,proto3" json:"sourceLat,omitempty"`
	SourceLng            float64  `protobuf:"fixed64,3,opt,name=sourceLng,proto3" json:"sourceLng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocationRequest) Reset()         { *m = GetLocationRequest{} }
func (m *GetLocationRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocationRequest) ProtoMessage()    {}
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d91fe6e1e35535, []int{3}
}

func (m *GetLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocationRequest.Unmarshal(m, b)
}
func (m *GetLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocationRequest.Marshal(b, m, deterministic)
}
func (m *GetLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocationRequest.Merge(m, src)
}
func (m *GetLocationRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocationRequest.Size(m)
}
func (m *GetLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocationRequest proto.InternalMessageInfo

func (m *GetLocationRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetLocationRequest) GetSourceLat() float64 {
	if m != nil {
		return m.SourceLat
	}
	return 0
}

func (m *GetLocationRequest) GetSourceLng() float64 {
	if m != nil {
		return m.SourceLng
	}
	return 0
}

type DriverDetails struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DriverLat            float64  `protobuf:"fixed64,4,opt,name=driverLat,proto3" json:"driverLat,omitempty"`
	DriverLong           float64  `protobuf:"fixed64,5,opt,name=driverLong,proto3" json:"driverLong,omitempty"`
	Distance             float64  `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverDetails) Reset()         { *m = DriverDetails{} }
func (m *DriverDetails) String() string { return proto.CompactTextString(m) }
func (*DriverDetails) ProtoMessage()    {}
func (*DriverDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d91fe6e1e35535, []int{4}
}

func (m *DriverDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverDetails.Unmarshal(m, b)
}
func (m *DriverDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverDetails.Marshal(b, m, deterministic)
}
func (m *DriverDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverDetails.Merge(m, src)
}
func (m *DriverDetails) XXX_Size() int {
	return xxx_messageInfo_DriverDetails.Size(m)
}
func (m *DriverDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DriverDetails proto.InternalMessageInfo

func (m *DriverDetails) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DriverDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DriverDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DriverDetails) GetDriverLat() float64 {
	if m != nil {
		return m.DriverLat
	}
	return 0
}

func (m *DriverDetails) GetDriverLong() float64 {
	if m != nil {
		return m.DriverLong
	}
	return 0
}

func (m *DriverDetails) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*LocationRequest)(nil), "proto.LocationRequest")
	proto.RegisterType((*GetLocationRequest)(nil), "proto.GetLocationRequest")
	proto.RegisterType((*DriverDetails)(nil), "proto.DriverDetails")
}

func init() {
	proto.RegisterFile("driverservice.proto", fileDescriptor_d6d91fe6e1e35535)
}

var fileDescriptor_d6d91fe6e1e35535 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xad, 0x4a, 0x72, 0xed, 0x29, 0xb5, 0xcd, 0xda, 0x14, 0xd5, 0x98, 0x62, 0x74, 0xf2,
	0xc9, 0x94, 0xf6, 0xd8, 0x63, 0x0d, 0x6e, 0x89, 0x21, 0x20, 0x63, 0xc8, 0x31, 0x6b, 0x69, 0x10,
	0x0b, 0xd2, 0xae, 0xa2, 0x1d, 0xf9, 0x8d, 0xf2, 0x2e, 0x79, 0xac, 0xb0, 0xab, 0x3f, 0x76, 0x12,
	0x43, 0x0e, 0x39, 0x69, 0xe6, 0x37, 0xab, 0xf9, 0x76, 0xe7, 0x1b, 0x98, 0x26, 0xa5, 0x38, 0x61,
	0xa9, 0xb1, 0x3c, 0x89, 0x18, 0xd7, 0x45, 0xa9, 0x48, 0x31, 0xdf, 0x7e, 0xc2, 0x7b, 0xf0, 0x0e,
	0x1a, 0x4b, 0x36, 0x01, 0xb7, 0x12, 0x49, 0xe0, 0x2c, 0x9d, 0xd5, 0x30, 0x32, 0x21, 0x9b, 0x81,
	0x8f, 0x39, 0x17, 0x59, 0xf0, 0xc9, 0xb2, 0x3a, 0x61, 0x0c, 0x3c, 0xc9, 0x73, 0x0c, 0x5c, 0x0b,
	0x6d, 0xcc, 0x16, 0x30, 0xcc, 0xb8, 0xa6, 0x4c, 0xa5, 0x42, 0x06, 0xde, 0xd2, 0x59, 0xb9, 0xd1,
	0x19, 0x84, 0x77, 0x30, 0x88, 0x50, 0x17, 0x4a, 0x6a, 0x64, 0x3f, 0x00, 0x34, 0x71, 0xaa, 0xf4,
	0x5f, 0x95, 0xa0, 0x15, 0xf3, 0xa3, 0x0b, 0x62, 0xba, 0x0b, 0x7d, 0x7b, 0x63, 0x25, 0x07, 0x91,
	0x8d, 0x59, 0x00, 0x9f, 0x73, 0xd4, 0x9a, 0xa7, 0xad, 0x68, 0x9b, 0x86, 0x08, 0xe3, 0x9d, 0x8a,
	0x39, 0x09, 0x25, 0x23, 0x7c, 0xa8, 0x50, 0xd3, 0x95, 0x67, 0x4c, 0xc0, 0xcd, 0x38, 0xd9, 0x8e,
	0x4e, 0x64, 0x42, 0x4b, 0x64, 0x6a, 0x9b, 0x19, 0x22, 0x53, 0xf3, 0x00, 0x12, 0x39, 0x6a, 0xe2,
	0x79, 0xd1, 0x3e, 0xa0, 0x03, 0xe1, 0x11, 0xd8, 0x16, 0xe9, 0x7d, 0xa5, 0x05, 0x0c, 0xb5, 0xaa,
	0xca, 0x18, 0x77, 0x9d, 0xde, 0x19, 0x5c, 0x54, 0x3b, 0xed, 0x33, 0x08, 0x1f, 0x1d, 0xf8, 0xba,
	0xb1, 0x2e, 0x6d, 0x90, 0xb8, 0xc8, 0xf4, 0x47, 0x0d, 0xa9, 0x2d, 0x37, 0x37, 0xf1, 0x6a, 0xad,
	0x0e, 0x18, 0x13, 0x9a, 0x44, 0xc9, 0x34, 0xf0, 0x6d, 0xf9, 0x82, 0xb0, 0x39, 0x0c, 0x12, 0xa1,
	0x89, 0xcb, 0x18, 0x83, 0xbe, 0xad, 0x76, 0xf9, 0xaf, 0xa7, 0xee, 0x9e, 0xfb, 0x7a, 0x9b, 0xd8,
	0x4f, 0x18, 0xed, 0x49, 0x95, 0x68, 0xb6, 0x68, 0x67, 0x0c, 0x67, 0x5f, 0xea, 0x0d, 0x5b, 0x1b,
	0x32, 0x1f, 0x37, 0x49, 0xbb, 0x02, 0x61, 0x8f, 0xfd, 0x81, 0xd1, 0xa1, 0x48, 0x38, 0x61, 0x3b,
	0x52, 0xf6, 0xad, 0x39, 0xf4, 0x6a, 0xc6, 0xd7, 0x7e, 0xfe, 0x07, 0xd3, 0x2d, 0x52, 0x7d, 0x85,
	0xff, 0xb2, 0xeb, 0xf0, 0xbd, 0x39, 0xf9, 0xd6, 0xa8, 0xf9, 0xac, 0x29, 0xbd, 0x18, 0x6f, 0xd8,
	0x3b, 0xf6, 0x2d, 0xfe, 0xfd, 0x1c, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xcc, 0xbb, 0x2f, 0x1e, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriverServiceClient interface {
	StoreUserLogin(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	UpdateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Response, error)
	GetDriverInLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*DriverDetails, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) StoreUserLogin(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.DriverService/StoreUserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.DriverService/UpdateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetDriverInLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*DriverDetails, error) {
	out := new(DriverDetails)
	err := c.cc.Invoke(ctx, "/proto.DriverService/GetDriverInLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
type DriverServiceServer interface {
	StoreUserLogin(context.Context, *User) (*Response, error)
	UpdateLocation(context.Context, *LocationRequest) (*Response, error)
	GetDriverInLocation(context.Context, *GetLocationRequest) (*DriverDetails, error)
}

// UnimplementedDriverServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDriverServiceServer struct {
}

func (*UnimplementedDriverServiceServer) StoreUserLogin(ctx context.Context, req *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreUserLogin not implemented")
}
func (*UnimplementedDriverServiceServer) UpdateLocation(ctx context.Context, req *LocationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (*UnimplementedDriverServiceServer) GetDriverInLocation(ctx context.Context, req *GetLocationRequest) (*DriverDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriverInLocation not implemented")
}

func RegisterDriverServiceServer(s *grpc.Server, srv DriverServiceServer) {
	s.RegisterService(&_DriverService_serviceDesc, srv)
}

func _DriverService_StoreUserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).StoreUserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DriverService/StoreUserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).StoreUserLogin(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DriverService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetDriverInLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetDriverInLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DriverService/GetDriverInLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetDriverInLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DriverService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreUserLogin",
			Handler:    _DriverService_StoreUserLogin_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _DriverService_UpdateLocation_Handler,
		},
		{
			MethodName: "GetDriverInLocation",
			Handler:    _DriverService_GetDriverInLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverservice.proto",
}
